using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace NEA___Boolean_and_Binary_Algebra_Revision_Tool
{
    /// <summary>
    /// Interaction logic for AutoGenerateQuestionsMenu_HelpPage.xaml
    /// </summary>
    public partial class AutoGeneratedQuestionsMenu_HelpPage : Page
    {
        public AutoGeneratedQuestionsMenu_HelpPage()
        {
            InitializeComponent();
        }
        /// <summary>
        /// methods to navigate from this menu
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>

        private void AutoGeneratedQuestionsMenu_HelpPage_ReturnToMain_Button_Click(object sender, RoutedEventArgs e)
        {
            NavigationService.Navigate(new MainMenu());
        }

        private void ReturnToAutoGeneratedQuestionsMenu_Button_Click(object sender, RoutedEventArgs e)
        {
            NavigationService.Navigate(new AutoGeneratedQuestionsMenu());
        }

    }
}
