using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace NEA___Boolean_and_Binary_Algebra_Revision_Tool
{
    /// <summary>
    /// Interaction logic for MainMenu.xaml
    /// </summary>
    public partial class MainMenu : Page
    {
        public MainMenu()
        {
            InitializeComponent();
        }
        /// <summary>
        /// methods to navigate from this menu
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void MainMenu_AutoGenQuesButton_Click(object sender, RoutedEventArgs e)
        {
            NavigationService.Navigate(new AutoGeneratedQuestionsMenu());
        }

        private void MainMenu_EnterQuesButton_Click(object sender, RoutedEventArgs e)
        {
            NavigationService.Navigate(new EnterUserQuestionsMenu());
        }

        private void MainMenu_SearchDBButton_Click(object sender, RoutedEventArgs e)
        {
            NavigationService.Navigate(new SearchDatabaseMenu());
        }
    }
}